version: '3.3'
services:
  db:
    container_name: "mp_helper_db"
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "${PORT}:5432"
    volumes:
      - mp_helper_volume:/home

volumes:
  mp_helper_volume: