"""fixes

Revision ID: 2168dd2fc0be
Revises: eda903124c93
Create Date: 2023-05-24 20:50:25.619186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2168dd2fc0be'
down_revision = 'eda903124c93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('post_name', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_group_id'), 'active', ['group_id'], unique=False)
    op.drop_index('ix_forecast_group_id', table_name='forecast')
    op.drop_table('forecast')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('post_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reach_daily', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='forecast_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='forecast_pkey')
    )
    op.create_index('ix_forecast_group_id', 'forecast', ['group_id'], unique=False)
    op.drop_index(op.f('ix_active_group_id'), table_name='active')
    op.drop_table('active')
    # ### end Alembic commands ###
