"""add cost to active model

Revision ID: 482b601b0723
Revises: 51978413cdea
Create Date: 2023-06-08 02:24:32.658804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482b601b0723'
down_revision = '51978413cdea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active', sa.Column('cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active', 'cost')
    # ### end Alembic commands ###
