"""fixes

Revision ID: 9779edb451e6
Revises: 2168dd2fc0be
Create Date: 2023-05-24 21:26:22.537740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9779edb451e6'
down_revision = '2168dd2fc0be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
