"""add cookies

Revision ID: b790e752fbcd
Revises: b0d235ae8b0b
Create Date: 2023-05-22 16:16:27.028986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b790e752fbcd'
down_revision = 'b0d235ae8b0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookies',
    sa.Column('remixsid', sa.String(), nullable=False),
    sa.Column('remixnsid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('remixsid', 'remixnsid')
    )
    op.add_column('forecast', sa.Column('reach_daily', sa.Integer(), nullable=True))
    op.drop_column('forecast', 'coverage_daily')
    op.add_column('stats', sa.Column('reach_daily', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('reach_all', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('reach_followers', sa.Integer(), nullable=True))
    op.drop_column('stats', 'coverage_all')
    op.drop_column('stats', 'coverage_followers')
    op.drop_column('stats', 'coverage_daily')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('coverage_daily', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('coverage_followers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('coverage_all', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('stats', 'reach_followers')
    op.drop_column('stats', 'reach_all')
    op.drop_column('stats', 'reach_daily')
    op.add_column('forecast', sa.Column('coverage_daily', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('forecast', 'reach_daily')
    op.drop_table('cookies')
    # ### end Alembic commands ###
