"""fixes

Revision ID: fac37bb7e2fd
Revises: 9779edb451e6
Create Date: 2023-05-24 21:31:42.077344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac37bb7e2fd'
down_revision = '9779edb451e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('active_group_id_fkey', 'active', type_='foreignkey')
    op.create_foreign_key(None, 'active', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('stats_group_id_fkey', 'stats', type_='foreignkey')
    op.create_foreign_key(None, 'stats', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.create_foreign_key('stats_group_id_fkey', 'stats', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'active', type_='foreignkey')
    op.create_foreign_key('active_group_id_fkey', 'active', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
