"""fixes

Revision ID: 51978413cdea
Revises: fac37bb7e2fd
Create Date: 2023-05-24 22:39:48.771388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51978413cdea'
down_revision = 'fac37bb7e2fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active', 'post_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active', sa.Column('post_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
