"""upgrade cookies

Revision ID: eda903124c93
Revises: b790e752fbcd
Create Date: 2023-05-22 17:29:14.797029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda903124c93'
down_revision = 'b790e752fbcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookies', sa.Column('hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cookies', 'hash')
    # ### end Alembic commands ###
